# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analysis.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalysis.proto\x12\x08\x61nalysis\"}\n\x0f\x41nalysisRequest\x12\x12\n\nvideo_path\x18\x01 \x01(\t\x12\x10\n\x08match_id\x18\x02 \x01(\t\x12\x13\n\x0b\x66rame_limit\x18\x03 \x01(\x05\x12\x11\n\tskip_json\x18\x04 \x01(\x08\x12\x1c\n\x14\x63onfidence_threshold\x18\x05 \x01(\x02\"\x81\x01\n\x10\x41nalysisResponse\x12\x10\n\x08match_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x10\n\x08progress\x18\x03 \x01(\x02\x12\x0f\n\x07message\x18\x04 \x01(\t\x12(\n\x06result\x18\x05 \x01(\x0b\x32\x18.analysis.AnalysisResult\"\xc8\x02\n\x0e\x41nalysisResult\x12\x10\n\x08match_id\x18\x01 \x01(\t\x12\x14\n\x0ctotal_frames\x18\x02 \x01(\x05\x12\x17\n\x0fplayers_tracked\x18\x03 \x01(\x05\x12\x1b\n\x13tracking_video_path\x18\x04 \x01(\t\x12\x1a\n\x12tracking_json_path\x18\x05 \x01(\t\x12\x1b\n\x13\x62\x61\x63kline_video_path\x18\x06 \x01(\t\x12\x1a\n\x12heatmap_video_path\x18\x07 \x01(\t\x12 \n\x18possession_analysis_path\x18\x08 \x01(\t\x12\x1c\n\x14\x61nimation_video_path\x18\t \x01(\t\x12\x1f\n\x17processing_time_seconds\x18\n \x01(\x01\x12\x0b\n\x03\x66ps\x18\x0b \x01(\x01\x12\x15\n\rerror_message\x18\x0c \x01(\t2Z\n\x0f\x41nalysisService\x12G\n\x0c\x41nalyzeVideo\x12\x19.analysis.AnalysisRequest\x1a\x1a.analysis.AnalysisResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ANALYSISREQUEST']._serialized_start=28
  _globals['_ANALYSISREQUEST']._serialized_end=153
  _globals['_ANALYSISRESPONSE']._serialized_start=156
  _globals['_ANALYSISRESPONSE']._serialized_end=285
  _globals['_ANALYSISRESULT']._serialized_start=288
  _globals['_ANALYSISRESULT']._serialized_end=616
  _globals['_ANALYSISSERVICE']._serialized_start=618
  _globals['_ANALYSISSERVICE']._serialized_end=708
# @@protoc_insertion_point(module_scope)
